"""empty message

Revision ID: 0405dd2fe0b3
Revises: d4d9fabc9d02
Create Date: 2017-04-06 13:09:23.394441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0405dd2fe0b3'
down_revision = 'd4d9fabc9d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('inventory_ibfk_2', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'items', ['item_id'], ['id'])
    op.drop_column('inventory', 'item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('item', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key('inventory_ibfk_2', 'inventory', 'items', ['item'], ['id'])
    op.drop_column('inventory', 'item_id')
    # ### end Alembic commands ###
