"""empty message

Revision ID: 0f0477f296d7
Revises: 33f34dcd6b8d
Create Date: 2017-04-06 21:15:06.295216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0477f296d7'
down_revision = '33f34dcd6b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_roles', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'last_update')
    op.drop_column('user_roles', 'create_date')
    # ### end Alembic commands ###
