"""empty message

Revision ID: 33f34dcd6b8d
Revises: 9b1c8f67fa8a
Create Date: 2017-04-06 20:37:50.655409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33f34dcd6b8d'
down_revision = '9b1c8f67fa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_types', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('attributes', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('character_notes', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('character_notes', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('experience_log', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('experience_log', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.drop_column('experience_log', 'award_date')
    op.add_column('inventory', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('inventory', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'create_date')
    op.drop_column('inventory', 'last_update')
    op.drop_column('inventory', 'create_date')
    op.add_column('experience_log', sa.Column('award_date', mysql.DATETIME(), nullable=True))
    op.drop_column('experience_log', 'last_update')
    op.drop_column('experience_log', 'create_date')
    op.drop_column('character_notes', 'last_update')
    op.drop_column('character_notes', 'create_date')
    op.drop_column('attributes', 'create_date')
    op.drop_column('attribute_types', 'create_date')
    # ### end Alembic commands ###
