"""empty message

Revision ID: 66a249fe9d40
Revises: 9b76c646bc0b
Create Date: 2017-04-06 22:34:55.443166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a249fe9d40'
down_revision = '9b76c646bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'characters', ['character'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_2', 'users', 'users', ['character'], ['id'])
    # ### end Alembic commands ###
