"""empty message

Revision ID: 9b1c8f67fa8a
Revises: bab5058c55f4
Create Date: 2017-04-06 17:43:34.042277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b1c8f67fa8a'
down_revision = 'bab5058c55f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('char_attr', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attributes', 'character_attributes', ['char_attr'], ['id'])
    op.add_column('character_attributes', sa.Column('character_id', sa.Integer(), nullable=True))
    op.drop_constraint('character_attributes_ibfk_1', 'character_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'character_attributes', 'characters', ['character_id'], ['id'])
    op.drop_column('character_attributes', 'character_att_id')
    op.drop_constraint('characters_ibfk_1', 'characters', type_='foreignkey')
    op.drop_column('characters', 'attribute_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('attribute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_1', 'characters', 'character_attributes', ['attribute_id'], ['id'])
    op.add_column('character_attributes', sa.Column('character_att_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'character_attributes', type_='foreignkey')
    op.create_foreign_key('character_attributes_ibfk_1', 'character_attributes', 'attributes', ['character_att_id'], ['id'])
    op.drop_column('character_attributes', 'character_id')
    op.drop_constraint(None, 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'char_attr')
    # ### end Alembic commands ###
