"""empty message

Revision ID: 9b76c646bc0b
Revises: fc166b938d92
Create Date: 2017-04-06 22:33:14.735145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b76c646bc0b'
down_revision = 'fc166b938d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('character', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['character'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'character')
    # ### end Alembic commands ###
