"""empty message

Revision ID: fc166b938d92
Revises: 0f0477f296d7
Create Date: 2017-04-06 22:28:28.393183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc166b938d92'
down_revision = '0f0477f296d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characters_ibfk_2', 'characters', type_='foreignkey')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_2', 'characters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
